# Generated by Django 4.2.13 on 2024-06-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_shoe_color_alter_shoe_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shoe')),
            ],
            options={
                'unique_together': {('customer', 'shoe')},
            },
        ),
    ]
